=== tanhw/icap/web/target/classes/queryFrame/uiColumn/uiColumn.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by zg (EMBRACE) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.000">
	<xs:element name="Root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Column" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>显示字段定义</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="columnName" use="required">
							<xs:annotation>
								<xs:documentation>显示字段名字</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="field" use="required">
							<xs:annotation>
								<xs:documentation>hibernate对于的字段名称</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="width">
							<xs:annotation>
								<xs:documentation>显示列宽度控制，不输入默认是100</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="0"/>
									<xs:maxInclusive value="1000"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="isSort" type="xs:boolean">
							<xs:annotation>
								<xs:documentation>是否运行排序，不输入默认不支持排序</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="align">
							<xs:annotation>
								<xs:documentation>页面显示对齐方式</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="left"/>
									<xs:enumeration value="center"/>
									<xs:enumeration value="right"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="formatter">
							<xs:annotation>
								<xs:documentation>进行数据显示的转换</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="styler">
							<xs:annotation>
								<xs:documentation>单元格样式</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== tanhw/icap/web/target/classes/queryFrame/uiColumn/tPosTmxData.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uiColumn.xsd">
	<Column columnName="程序名称" field="filename" align="center" width="200"  isSort="true"/>
	<Column columnName="机构ID" field="unitid" align="center" width="100"  isSort="true"/>
	<Column columnName="商户ID" field="branchid" align="center" width="100"  isSort="true"/>
	<Column columnName="商户序号" field="merseq" align="center" width="100"  isSort="true"/>
	<Column columnName="pos品牌" field="posbrand" align="center" width="100"  isSort="true" formatter="posbrandDesc"/>
	<Column columnName="存放目录" field="filepath" align="center" width="300"  isSort="true"/>
	<Column columnName="版本号" field="version" align="center" width="100"  isSort="true"/>
	<Column columnName="程序大小" field="filesize" align="center" width="100"  isSort="true"/>
	<Column columnName="程序功能" field="filefunc" align="center" width="100"  isSort="true"/>
</Root>

=== tanhw/icap/web/target/classes/queryFrame/uiColumn/tBankInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uiColumn.xsd">
	<Column columnName="银行ID" field="bankid" align="center" width="100" isSort="true"/>
	<Column columnName="机构ID" field="unitid" align="center" width="100" isSort="true"/>
	<Column columnName="银行代码" field="bankcode" align="center" width="100" isSort="true"/>
	<Column columnName="银行名称" field="bankname" align="center" width="150"  isSort="true" />
	<Column columnName="银行地址" field="bankaddr" align="center" width="150" isSort="true"/>
	<Column columnName="银行联系人" field="bankcontact" align="center" width="100" isSort="true"/>
	<Column columnName="银行联系人电话" field="banktele" align="center" width="100" isSort="true"/>
	<Column columnName="银行传真" field="bankfax" align="center" width="100" isSort="true"/>
	<Column columnName="银行邮箱" field="bankmail" align="center" width="120"  isSort="true"/>
	<Column columnName="创建时间" field="createtime" align="center" width="150" isSort="true" formatter="createtimeDesc"/>
</Root>

=== tanhw/icap/web/target/classes/queryFrame/uiColumn/tPosinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uiColumn.xsd">
	<Column columnName="POS机ID" field="posid" align="center" width="100"  isSort="true"/>
	<Column columnName="POS类别" field="postype" align="center" width="100" isSort="true" formatter="postypeDesc"/>
	<Column columnName="机构ID" field="unitid" align="center" width="100"  isSort="true" />
	<Column columnName="机构名称" field="unitname" align="center" width="100"  isSort="true" />
	<Column columnName="商户序号" field="merseq" align="center" width="100"  isSort="true" />
	<Column columnName="商户名称" field="branchchn" align="center" width="100"  isSort="true" />
	<Column columnName="区域商户" field="companyname" align="center" width="100"  isSort="true" />
	<Column columnName="商户编号" field="branchid" align="center" width="100"  isSort="true" />
	<Column columnName="车辆编号" field="busid" align="center" width="100" isSort="true" />
	<Column columnName="车牌号" field="tlic" align="center" width="100" isSort="true" />
	<Column columnName="SAM卡号" field="samid" align="center" width="120" isSort="true" />
	<Column columnName="POS状态" field="status" align="center" width="150" isSort="true" formatter="statusDesc"/>
	<Column columnName="POS品牌" field="posbrand" align="center" width="120" isSort="true" formatter="posbrandDesc"/>
	<Column columnName="录入时间" field="createtime" align="center" width="150" isSort="true" formatter="createtimeDesc"/>
	<Column columnName="主密钥下载标志" field="tmkdownflag" align="center" width="100" isSort="true" formatter="tmkdownflagDesc"/>
	<Column columnName="keya密钥下载标志" field="keyadownflag" align="center" width="100" isSort="true" formatter="keyadownflagDesc"/>
	<Column columnName="POS当前批次号" field="batchno" align="center" width="120" isSort="true"/>
	<Column columnName="POS累积流水号" field="postraceno" align="center" width="150" isSort="true"/>
	<Column columnName="POS终端序列号" field="termseq" align="center" width="120" isSort="true"/>
	<Column columnName="交易超时时间" field="timeout" align="center" width="150" isSort="true"/>
	<Column columnName="单笔交易最大金额" field="maxmoney" align="center" width="120" isSort="true" formatter="maxmoneyDesc"/>
	<Column columnName="累积交易最大金额" field="totalmoney" align="center" width="120" isSort="true" formatter="totalmoneyDesc"/>
	<Column columnName="设备物理编号" field="physicsno" align="center" width="100" isSort="true"/>
	<Column columnName="最后密钥下载时间" field="lasttimestamp" align="center" width="120" isSort="true" formatter="lasttimestampDesc"/>
</Root>

=== tanhw/icap/web/target/classes/queryFrame/uiColumn/tMerop.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uiColumn.xsd">
	<Column columnName="序号" field="meropseq" align="center" width="100" isSort="true"/>
	<Column columnName="商户编号" field="merseq" align="center" width="100" isSort="true"/>
	<Column columnName="登录名" field="loginname" align="center" width="100" isSort="true"/>
	<Column columnName="创建时间" field="createtime" align="center" width="150"  isSort="true" formatter="createtimeDesc"/>
	<Column columnName="真实姓名" field="realname" align="center" width="100" isSort="true"/>
	<Column columnName="电话" field="phone" align="center" width="100" isSort="true"/>
	<Column columnName="邮箱" field="mail" align="center" width="100" isSort="true"/>
	<Column columnName="角色序号" field="roeseq" align="center" width="100" isSort="true"/>
	<Column columnName="是否有效" field="isactive" align="center" width="100"  isSort="true" formatter="isactiveDesc"/>
	<Column columnName="修改时间" field="modifytime" align="center" width="150" isSort="true" formatter="modifytimeDesc"/>
	<Column columnName="上次登录时间" field="lastlogtime" align="center" width="150" isSort="true" formatter="lastlogtimeDesc"/>
	<Column columnName="上次登录IP" field="lastlogip" align="center" width="150" isSort="true"/>
	<Column columnName="机构ID" field="unitid" align="center" width="100" isSort="true" />
	<Column columnName="门店序号" field="storeseq" align="center" width="100" isSort="true" />
</Root>

=== tanhw/icap/web/target/classes/queryFrame/uiColumn/tMenu.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uiColumn.xsd">
	<Column columnName="菜单编号" field="id" align="center" width="100"  isSort="true"/>
	<Column columnName="菜单名字" field="text" align="center" width="100" isSort="true"/>
	<Column columnName="菜单描述" field="menudesc" align="center" width="150"  isSort="true"/>
	<Column columnName="菜单url" field="url" align="center" width="180" isSort="true"/>
	<Column columnName="上级菜单" field="upmenu" align="center" width="150"  isSort="true"/>
	<Column columnName="菜单级别" field="menuLevel" align="center" width="150"  formatter="menuLevelDesc" isSort="true" />
	<Column columnName="菜单位置" field="position" align="center" width="150" formatter="menuPositionDesc" isSort="true"/>
	<Column columnName="菜单权限类型" field="menutype" align="center" width="150"  isSort="true"/>
	<Column columnName="菜单类型" field="menukind" align="center" width="150" formatter="menukindDesc" isSort="true"/>
</Root>

=== tanhw/icap/web/src/main/resources/queryFrame/uiColumn/tDict.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uiColumn.xsd">
	<Column columnName="字典编号" field="ccode" align="center" width="100"  isSort="false"/>
	<Column columnName="内容值	" field="cvalue" align="center" width="100" isSort="false"/>
	<Column columnName="内容描述	" field="cdesc" align="center" width="100" isSort="false"/>
	<Column columnName="字典类型" field="ctype" align="center" width="150"  isSort="true"/>
	<Column columnName="是否有效" field="isactive" align="center" width="180" formatter="activeDesc" isSort="true"/>
	<Column columnName="机构ID" field="unitid" align="center" width="180" isSort="true"/>
	<Column columnName="父级编号" field="cupcode" align="center" width="180" isSort="true"/>
</Root>

=== tanhw/icap/web/target/classes/queryFrame/uiColumn/tPosKeyInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uiColumn.xsd">
	<Column columnName="终端编号" field="posid" align="center" width="120"  isSort="true"/>
	<Column columnName="机构ID" field="unitid" align="center" width="100"  isSort="true"/>
	<Column columnName="商户ID" field="branchid" align="center" width="120"  isSort="true"/>
	<Column columnName="商户序号" field="merseq" align="center" width="120"  isSort="true"/>
	<Column columnName="终端主密钥" field="tmk" align="center" width="100"  isSort="true"/>
	<Column columnName="终端主密钥校验值" field="tmkchkvalue" align="center" width="100"  isSort="true"/>
	<Column columnName="终端传输密钥" field="kek" align="center" width="100"  isSort="true"/>
	<Column columnName="终端MAC密钥" field="mak" align="center" width="100"  isSort="true"/>
	<Column columnName="终端MAC密钥校验值" field="makchkvalue" align="center" width="120"  isSort="true"/>
	<Column columnName="终端PIN密钥" field="pik" align="center" width="120"  isSort="true"/>
	<Column columnName="终端PIN密钥校验值" field="pikchkvalue" align="center" width="120"  isSort="true"/>
	<Column columnName="终端TRK密钥" field="trk" align="center" width="120"  isSort="true"/>
	<Column columnName="终端TRK密钥校验值" field="trkchkvalue" align="center" width="120"  isSort="true"/>
</Root>

=== tanhw/icap/web/target/classes/queryFrame/uiColumn/tUnit.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uiColumn.xsd">
	<Column columnName="机构号" field="unitid" align="center" width="100"  isSort="true"/>
	<Column columnName="机构名称" field="unitname" align="center" width="100" isSort="true"/>
	<Column columnName="机构联系人" field="unitcontact" align="center" width="120"  isSort="true"/>
	<Column columnName="机构联系电话" field="unittele" align="center" width="120" isSort="true" />
	<Column columnName="机构邮箱" field="unitmail" align="center" width="120"  isSort="true"/>
	<Column columnName="机构传真" field="unitfax" align="center" width="120" isSort="true"/>
	<Column columnName="父级机构ID" field="parentid" align="center" width="100"  isSort="true"/>
	<Column columnName="机构描述" field="unitdesc" align="center" width="150"  isSort="true"/>
	<Column columnName="机构地址" field="unitaddr" align="center" width="180" isSort="true"/>
	<Column columnName="机构种类" field="unitkind" align="center" width="120" isSort="true" formatter="unitkindDesc"/>
</Root>
