=== tanhw/icap/web/target/classes/queryFrame/uiColumn/uiColumn.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by zg (EMBRACE) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.000">
	<xs:element name="Root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Column" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>显示字段定义</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="columnName" use="required">
							<xs:annotation>
								<xs:documentation>显示字段名字</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="field" use="required">
							<xs:annotation>
								<xs:documentation>hibernate对于的字段名称</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="width">
							<xs:annotation>
								<xs:documentation>显示列宽度控制，不输入默认是100</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="0"/>
									<xs:maxInclusive value="1000"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="isSort" type="xs:boolean">
							<xs:annotation>
								<xs:documentation>是否运行排序，不输入默认不支持排序</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="align">
							<xs:annotation>
								<xs:documentation>页面显示对齐方式</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="left"/>
									<xs:enumeration value="center"/>
									<xs:enumeration value="right"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="formatter">
							<xs:annotation>
								<xs:documentation>进行数据显示的转换</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="styler">
							<xs:annotation>
								<xs:documentation>单元格样式</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== tanhw/icap/web/target/classes/queryFrame/uiColumn/tPosfac.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uiColumn.xsd">
	<Column columnName="厂商ID" field="factoryid" align="center" width="100" isSort="true"/>
	<Column columnName="厂商代码" field="faccode" align="center" width="100" isSort="true"/>
	<Column columnName="厂商名称" field="facname" align="center" width="150"  isSort="true" />
	<Column columnName="厂商地址" field="facaddr" align="center" width="180"  isSort="true" />
	<Column columnName="厂商联系人" field="faccontact" align="center" width="100"  isSort="true" />
	<Column columnName="厂商电话" field="factele" align="center" width="120" isSort="true" />
	<Column columnName="厂商邮箱" field="facmail" align="center" width="150" isSort="true" />
	<Column columnName="厂商传真" field="facfax" align="center" width="120" isSort="true" />
	<Column columnName="厂商描述" field="facdesc" align="center" width="180" isSort="true"/>
	<Column columnName="供应设备描述" field="facprodesc" align="center" width="150" isSort="true"/>
</Root>

=== tanhw/icap/web/src/main/resources/queryFrame/uiColumn/tAdmin.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uiColumn.xsd">
	<Column columnName="登录名" field="loginname" align="center" width="100" isSort="true"/>
	<Column columnName="真实姓名" field="realname" align="center" width="100"  isSort="true" />
	<Column columnName="是否有效" field="isactive" align="center" width="100"  isSort="true" formatter="isactiveDesc"/>
	<Column columnName="角色序号" field="roeseq" align="center" width="100"  isSort="true" />
	<Column columnName="创建时间" field="createtime" align="center" width="150" isSort="true" formatter="createtimeDesc"/>
	<Column columnName="修改时间" field="modifytime" align="center" width="150" isSort="true" formatter="modifytimeDesc"/>
	<Column columnName="上次登录时间" field="lastlogtime" align="center" width="150" isSort="true" formatter="lastlogtimeDesc"/>
	<Column columnName="上次登录IP" field="lastlogip" align="center" width="150" isSort="true"/>
	<Column columnName="电话" field="phone" align="center" width="100" isSort="true"/>
	<Column columnName="邮箱" field="mail" align="center" width="120"  isSort="true"/>
</Root>

=== tanhw/icap/web/src/main/resources/queryFrame/uiColumn/tMerchantinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uiColumn.xsd">
	<Column columnName="商户序号" field="merseq" align="center" width="100" isSort="true"/>
	<Column columnName="商户编号" field="branchid" align="center" width="100" isSort="true"/>
	<Column columnName="机构ID" field="unitid" align="center" width="100" isSort="true"/>
	<Column columnName="银行收单商户号" field="bankmerid" align="center" width="100" isSort="true"/>
	<Column columnName="区域公司ID" field="acompanyid" align="center" width="100" isSort="true" />
	<Column columnName="商户英文名" field="brancheng" align="center" width="100"  isSort="true" />
	<Column columnName="商户中文名" field="branchchn" align="center" width="100" isSort="true"/>
	<Column columnName="商户负责人" field="stfid" align="center" width="100" isSort="true"/>
	<Column columnName="商户状态" field="branchstate" align="center" width="100" isSort="true" formatter="branchstateDesc"/>
	<Column columnName="商户描述" field="branchdesc" align="center" width="100" isSort="true"/>
	<Column columnName="商户地址" field="branchadre" align="center" width="150"  isSort="true"/>
	<Column columnName="商户电话" field="branchphone" align="center" width="120" isSort="true" />
	<Column columnName="手续费序号" field="feeseq" align="center" width="100" isSort="true"/>
	<Column columnName="商户logo" field="branlogo" align="center" width="150" isSort="true"/>
	<Column columnName="所在城市" field="brancity" align="center" width="100" isSort="true" />
	<Column columnName="传真" field="fax" align="center" width="100" isSort="true" />
	<Column columnName="商户网站" field="site" align="center" width="150" isSort="true" />
	<Column columnName="POS终端数量" field="poscount" align="center" width="100" isSort="true" />
	<Column columnName="签约时间" field="signtime" align="center" width="150" isSort="true" />
</Root>

=== tanhw/icap/web/src/main/resources/queryFrame/uiColumn/tLog.xml
<?xml version="1.0" encoding="UTF-8"?>
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="uiColumn.xsd">
	<Column columnName="操作员ID" field="oplogname" align="center" width="80" isSort="true"/>
	<Column columnName="操作员姓名" field="oprealname" align="center" width="100"  isSort="true"/>
	<Column columnName="日志描述" field="opdesc" align="center" width="280" isSort="true"/>
	<Column columnName="机构ID" field="unitid" align="center" width="100"  isSort="true" />
	<Column columnName="操作是否成功" field="opflag" align="center" width="80" isSort="true" formatter="opflagDesc"/>
	<Column columnName="操作时间" field="optime" align="center" width="150" isSort="true" formatter="optimeDesc"/>
	<Column columnName="来源IP" field="opip" align="center" width="150" isSort="true"/>
</Root>
